# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rx', models.CharField(max_length=255, verbose_name='regular expression')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
            ],
            options={
                'verbose_name_plural': 'blacklist items',
                'verbose_name': 'blacklist item',
            },
        ),
    ]
