# DOCKER FREE DEVELOPMENT CONFIG WITH DEBUG == True
# DJANGO DATABASE SETTINGS
db:
  engine: 'django.db.backends.postgresql'
  host: '127.0.0.1'
  port: 5432
  database: 'msa_mailer'
  user: 'msa_mailer'
  password: 'msa_mailer'

# SENTRY RAVEN SETUP
raven:
  dsn: ''

# DJANGO ALLOWED_HOSTS
hosts:
  - 'localhost'
  - 'msa-mailer'

# DJANGO SERVER MAIL SETTINGS
mail:
  backend: 'django.core.mail.backends.smtp.EmailBackend'
  server_email: 'noreply@example.com'
  from: 'NOREPLY <noreply@example.com>'
  host: 'smtp.example.com'
  port: 587
  tls: true
  user: 'user@example.com'
  password: 'Guess'

# DJANGO CACHE
cache:
  locations:
    - 'localhost:6379'

# DJANGO CELERY BROKER
celery:
  broker: 'redis://127.0.0.1:6379/1'
  result_backend: 'redis://127.0.0.1:6379/15'
  workers: 2

# DJANGO CREATE SERVICE SUPERUSER
superuser:
  username: 'admin'
  password: 'password'
  email: 'admin@example.com'

debug: true

common:
  secret_key: 'secret'
